apiVersion: v1
kind: Service
metadata:
  name: getos-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: getos-api
    app.kubernetes.io/part-of: techchallenge-oficina
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: getos-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
