apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: approval-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: approval-api
    app.kubernetes.io/part-of: techchallenge-oficina
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: approval-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
