apiVersion: apps/v1
kind: Deployment
metadata:
  name: createos-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: createos-api
    app.kubernetes.io/part-of: techchallenge-oficina
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: createos-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: createos-api
        app.kubernetes.io/part-of: techchallenge-oficina
    spec:
      containers:
        - name: createos-api
          image: 903936907231.dkr.ecr.us-east-1.amazonaws.com/techchallenge-oficina-createos:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: createos-api-config
            - secretRef:
                name: oficina-api-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 100
            timeoutSeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 100
            timeoutSeconds: 30
            failureThreshold: 10
